### ISSUE TITLE
Orientation of Profile in mktunnel

### ISSUE THREAD

**Issue by gilesknap** [conqp/mcipc#20]
This is a subtle issue and may be intended behaviour but I found it confusing to use.  It you agree that this behaviour should be changed I will look into the implementation and submit a PR.

When you use the TOP_LEFT anchor in mktunnel the profile of the tunnel on screen looking North looks like the profile does in code.

e.g.
```
    p: Profile = [
        [Item.RED_WOOL.value, Item.AIR.value, Item.GREEN_WOOL.value],
        [Item.AIR.value, Item.AIR.value, Item.AIR.value],
        [Item.BLUE_WOOL.value, Item.AIR.value, Item.YELLOW_WOOL.value],
    ]
```
produces a red square in the top left.

However, if you use other anchors the result is that your profile is rotated about the TOP left or [0,0] in the profile lists.
I would have expected a translation only so that your profile still looks the same.

I guess it is useful to be able to rotate the profile, but would prefer a separate function to do so.

By example this image shows the above profile sent in all compas points. The left is TOP_LEFT and right is BOTTOM_RIGHT.
![image](https://user-images.githubusercontent.com/964827/103454533-0593fc80-4cdd-11eb-825a-73636d58ab96.png)

**Comment by gilesknap** [comment]
It occurs to me that numpy can support arbitrary python objects.

If we could describe profiles as a numpy array of Item we would be able to trivially rotate them as well as any other operation we can think of (map would be able to perform any function over the whole array).

This could then extend to cubes as well. 

It would be an excellent demo of the power of python.

**Comment by gilesknap** [comment]
I would also like an anchor for bottom middle and top middle. Use full for vertical tunnels. Trivial to supply with numpy.

**Comment by conqp** [comment]
While in general, I'm interested in extending the *builder* subsystem (which was intended as a playground for world manipulation methods), I also want to avoid introducing new dependencies to *mcipc*.
So while it is certainly possible to support numpy, I would want to refrain from pulling it in as a dependency in any way.
Currently I am lacking the time to further extend the builder subsystem.

Regarding the original issue of profile rotation, this really should not happen. I admit that I scribbled the code for the builder subsystem within a few hours and did not thoroughly test it. In fact I only tested it with symmetric profiles, so that I probably never saw this issue. If you have a patch at hand, I'd be happy to merge it.

**Comment by gilesknap** [comment]
OK, agreed that it is nice to keep the library dependencies light. 

I'll look at a fix to the rotation issue without resorting to numpy, 

I'll also experiment with using numpy arrays through duck typing like you did with functions that take Vec3. That way people that want to do interesting transforms etc can pull in numpy to help.

**Comment by gilesknap** [comment]
Your library works perfectly with numpy (maybe you already knew that!).

I created this fun demo:
https://github.com/gilesknap/mc-rcon-test/blob/main/test_cube.py

https://user-images.githubusercontent.com/964827/103475631-d944b280-4da6-11eb-8b28-4456e56bdf24.mp4

**Comment by conqp** [comment]
Outsourced builder subsystem to: https://github.com/conqp/mcwb
